mediaConfing: 
  host: "localhost"
  port: 8081
  storageRootPath: "./data/"
  routes:
    imageRoute: 
      name: "/images/"
      storageRoute: "images/"
    videoRoute: 
      name: "/videos/"
      storageRoute: "videos/"
  
